version: '2'
# Typical usage:
# Download Logfiles into folder logs
# docker-compose up
# Wait for logfile parsing
#
# Browse Kibana:
# http://localhost:5601/
# docker-compose down -v
#
# WWW: infos:
# https://elk-docker.readthedocs.io/
#
#
# Setup:
# add:
# vm.max_map_count = 262144
# to:
# /etc/sysctl.d/99-sysctl.conf/99-myfile.conf
#
# To enable: reboot or :-)
# sudo sysctl --system
#


services:
  logstash_ebegu:
    image: sebp/elk
    environment:
      - "TZ=Europe/Zurich"
    volumes:
      - "./input/:/input/"
      - "./conf.d:/etc/logstash/conf.d"
    ports:
      - "5601:5601"
#      - "9200:9200"
#      - "9300:9300"
#      - "5044:5044"
