version: '2'
services:
  EBEGU-MARIADB:
    image: healthcheck/mariadb
    environment:
      - MYSQL_DATABASE=ebegu
      - MYSQL_USER=ebegu
      - MYSQL_PASSWORD=ebegu
      - MYSQL_ROOT_PASSWORD=ebegu
    networks:
      - ebegu-net
    command: ['--character-set-server=utf8', '--collation-server=utf8_unicode_ci' ,'--verbose']
    #volumes:
      # Just specify a path and let the Engine create a volume
      #- "/var/lib/mysql"

  database-wait:
    image: digit/wait-for-mysql
    depends_on:
         - EBEGU-MARIADB
    networks:
      - ebegu-net

  EBEGU-WILDFLY:
    image: docker.dvbern.ch:5000/stadt-bern/ebegu-wildfly
    depends_on:
         - database-wait
    networks:
      - ebegu-net
    ports:
      - 8080:8080
      - 8443:8443
      - 9990:9990

  EBEGU-WEB:
    image: docker.dvbern.ch:5000/stadt-bern/ebegu-ngnix
    depends_on:
         - EBEGU-WILDFLY
    networks:
    - ebegu-net
    ports:
     - 80:80

networks:
  ebegu-net: